function [exceeds] = psp_compf1(f,cl,freq,max_cmp,label)

%[R, cm_1, cm_5] = psp_compf1(f,cl,freq,max_cmp,label)

% psp_compf1(f,cl,freq,max_cmp,label)
% Function to plot results of log ratio difference of spectra test
%  in current figure/subplot window.
% Use to plot output of sp2_compf() function, Confidence limits based on F test.
% This version based on hypothesis of equal spectra, i.e. log ratio test = 0.
%
% Copyright (C) 2008, David M. Halliday.
% This file is part of NeuroSpec.
%
%    NeuroSpec is free software; you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation; either version 2 of the License, or
%    (at your option) any later version.
%
%    NeuroSpec is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with NeuroSpec; if not, write to the Free Software
%    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%    NeuroSpec is available at:  http://www.neurospec.org/
%    Contact:  contact@neurospec.org
%
% f,cl     Ouput from difference of spectra routine, sp2_compf().
% freq     Frequency limit for plotting (Hz).
% max_cmp  Optional limits for y axis, should be +ve.
% label    Optional title instead of cl.what.
%
% psp_compf1(f,cl,freq,max_cmp,label)

if (nargin<3)
  error('Not enough input arguments')
end  

%freq_pts=round(freq/cl.df);
%Updated to support type 2 analysis
f_start=f(1,1,1);
freq_pts=round((freq-f_start)/cl.df)+1;

% Check this is output from sp2_compf.m
if (isfield(cl,'fcmp_c95u')==0)
  error('Results not generated by sp2_compf.m');
end
%Check freq range
[x,y]=size(f);
if (freq_pts>x)
  error('Requested frequency range too large.');
end
if (freq_pts<1)
  error('Requested frequency range too narrow.');
end

% Apply moving average filter to output - added by KD 25/04/18
f(:,2) = smooth(f(:,2),20);

f_max=freq_pts*cl.df;
uline=[f_start cl.fcmp_c95u; f_max cl.fcmp_c95u];  % Upper 95% confidence limit
lline=[f_start cl.fcmp_c95l; f_max cl.fcmp_c95l];  % Lower  95% confidence limit
zline=[f_start       0.0000; f_max       0.0000];  % Zero line, NULL value
plot(f(3:freq_pts,1),f(3:freq_pts,2),'k-',...
     uline(:,1),uline(:,2),'k-',...
     lline(:,1),lline(:,2),'k-',...
     zline(:,1),zline(:,2),'k--')
if nargin>3
  axis([0,freq,-max_cmp,+max_cmp]);
else  
  axis([0,freq,-Inf,Inf]);
end
%xlabel('Frequency (Hz)')
ylabel('Log ratio')
ylim([-0.8 0.8]) % KD addition
set(gca,'xticklabel',[]);

if (nargin>4)
  title(label);
else
 title(['fcmp: ',cl.what]);
end  


% ADDED BY KD 011018
% Return indices to positions where CIs are exceeded
exceeds = f(3:freq_pts,2);% < cl.fcmp_c95l | f(3:freq_pts,2) > cl.fcmp_c95u;
exceeds = find(exceeds);

return
% ADDED BY KD 280918
% Test hypothesis that both spectra are the same (Diggle p120)
U = max(f(3:freq_pts,2)); % Max ratio
L = min(f(3:freq_pts,2)); % Min ratio
R = U-L;

m=161; b1_1 = 0.403; b2_1=-0.0360; b3_1=1.567; b1_5 = 0.472; b2_5=-0.0493 ; b3_5=1.107;            
cm_1 = ((b1_1*log(m))/1-b2_1*log(m))+b3_1;
cm_5 = ((b1_5*log(m))/1-b2_5*log(m))+b3_5;







